### ISSUE TITLE
Spring Config Server

### ISSUE THREAD

**Issue by Muralidhar1001879** [SteeltoeOSS/Initializr#129]
The Config Values are returned as NULL for the scaffolded project - 'Spring Config Server', Please suggest if we can start using this for one of our Project.

**Comment by jkonicki** [comment]
@ccheetham Can you assist?

**Comment by Muralidhar1001879** [comment]
Hi ccheetham,

I have followed all the steps of https://steeltoe.io/app-configuration/get-started/springconfig
but the end result is that I am getting values [null, null] returned for Config Values, happy share the screen, please reach me out on the mail.

Regards,
Murali.

**Comment by ccheetham** [comment]
Hi @Muralidhar1001879 

Let's start by checking your config server.

I created a GitHub repository per the above docs:
  https://github.com/ccheetham/Spring-Config-Demo

Run your config server using the above repo.  I'm adding a `--debug` option  as it will help to ensure we're sending the expected request to the server:
```
$ docker run -it --rm --publish 8888:8888 steeltoeoss/config-server \
        --spring.cloud.config.server.git.uri=https://github.com/ccheetham/Spring-Config-Demo \
        --debug
...
2020-10-28 15:27:09.062  INFO 1 --- [           main] i.s.docker.configserver.ConfigServer     : Started ConfigServer in 4.878 seconds (JVM running for 5.632)
```

With the server listening, we can issue an HTTP request against it.  I'm using [httpie](https://httpie.org/) in this example, but you can use `curl` or a browser:

```
$ http http://localhost:8888/my-values/Development
HTTP/1.1 200
Connection: keep-alive
Content-Type: application/json
Date: Wed, 28 Oct 2020 15:31:31 GMT
Keep-Alive: timeout=60
Transfer-Encoding: chunked

{
    "label": null,
    "name": "my-values",
    "profiles": [
        "Development"
    ],
    "propertySources": [
        {
            "name": "https://github.com/ccheetham/Spring-Config-Demo/my-values.yml",
            "source": {
                "Value1": "some-val",
                "Value2": "another-val"
            }
        }
    ],
    "state": null,
    "version": "dce61c1d6243583eaca140ef00a4087685f44e22"
}
```

Note the URL path is formatted `appname/profile`, which in this case is `my-values/Development`.  The appname is the name of your application, or in the case of the example you're following, it's overridden in `appsettings.json`.  The profile is detected by Steeltoe (although be similarly overridden).

After issuing the above request, you should see something like the following in the Config Server output:

```
2020-10-28 15:36:51.802  INFO 1 --- [nio-8888-exec-7] o.s.c.c.s.e.NativeEnvironmentRepository  : Adding property source: file:/tmp/config-repo-13298186212758103778/my-values.yml
2020-10-28 15:36:51.803 DEBUG 1 --- [nio-8888-exec-7] m.m.a.RequestResponseBodyMethodProcessor : Using 'application/json', given [*/*] and supported [application/json]
2020-10-28 15:36:51.803 DEBUG 1 --- [nio-8888-exec-7] m.m.a.RequestResponseBodyMethodProcessor : Writing [Environment [name=my-values, profiles=[Development], label=null, propertySources=[PropertySource [na (truncated)...]
2020-10-28 15:36:51.804 DEBUG 1 --- [nio-8888-exec-7] o.s.web.servlet.DispatcherServlet        : Completed 200 OK
```

Note the penultimate message: _Writing [Environment [name=my-values, profiles=[Development],..._

If you see 
```
"Value1": "some-val",
"Value2": "another-val"
```
in your HTTP request output, then the Config Server is configured properly.

Now try your app.  If the `appsettings.json` has been configured per the example, you should see a similar message in the Config Server console to that we got when we issued the HTTP request.

If you're still getting null values, check the Config Server log for hints.

For example, this is what you might see if the app name is misconfigured and is instead being auto-detected:
```
2020-10-28 15:40:16.368 DEBUG 1 --- [nio-8888-exec-9] m.m.a.RequestResponseBodyMethodProcessor : Writing [Environment [name=SteeltoeExample, profiles=[Development], ...
```

**Comment by Muralidhar1001879** [comment]
Dear Cheetham,

Thank you very much for the response, the difference in the code I see is on the my-values.yml file.
when I run the container provided by you, its working for the URI that you have mentioned: https://github.com/ccheetham/Spring-Config-Demo
but when I try with my URI:  https://github.com/Muralidhar1001879/Spring-Config-Demo
its not returning result: the URi I have kept it public. my URI details are as below for a quick reference.


can you please help me out figure out what could be the issue.

Regards,
Muralidhar.k

**Comment by ccheetham** [comment]
I tried your repo and was able to reproduce the failure.

The issue has to do with branches.  Spring Config Server has the ability to pin a configuration to a branch/tag/commit.  If not specified, the branch `master` is assumed.

Since your repo has no branch `master`, no config is found.

Here are 2 HTTP requests that highlight the issue:

```
# request: default (master) branch
$ http http://localhost:8888/my-values/Development
HTTP/1.1 404
...
# request: specific (main) branch
$ http http://localhost:8888/my-values/Development/main
HTTP/1.1 200
...
```

To fix, specify the branch in `appsettings.yml`.  Spring Config Config Server refers to a branch/tag/commit as a `label`.  Here's the updated appsettings:

```
...
"cloud": {
            "config": {
                "uri": "http://localhost:8888",
                "validateCertificates": false,
                "label": "main"
            }
        }
...
```

After making the change, HTTP requests to the sample app should succeed to retrieve the values:
```
$ http http://localhost:5000/api/values
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Thu, 29 Oct 2020 11:50:02 GMT
Server: Kestrel
Transfer-Encoding: chunked

[
    "some-val",
    "another-val"
]
```
