### ISSUE TITLE
ValidateScopes in generated template

### ISSUE THREAD

**Issue by kimbell** [SteeltoeOSS/Initializr#130]
I created an app using the beta web generator at https://start.steeltoe.io
When I looked at the generated code, I noticed a line in program.cs

`.UseDefaultServiceProvider(configure => configure.ValidateScopes = false)`

What is the reasoning for disabling scope validation? It was added in .NET Core 2.0 to avoid DI mistakes.

**Comment by hananiel** [comment]
This was a temporary workaround for a bug we had. This will be removed in the new initializr.

**Comment by ccheetham** [comment]
Issue moved to [SteeltoeOSS/InitializrConfig #50](https://github.com/SteeltoeOSS/InitializrConfig/issues/50) via [**ZenHub**](https://www.zenhub.com/)
