### ISSUE TITLE
Spring Cloud Config Server adds incorrect dependency

### ISSUE THREAD

**Issue by macsux** [SteeltoeOSS/initializr#134]
Adding `Spring Cloud Config Server` adds `    <PackageReference Include="Steeltoe.Extensions.Configuration.config-serverCore" Version="3.0.1" />` which is invalid package

**Comment by ccheetham** [comment]
Issue moved to [SteeltoeOSS/InitializrConfig #41](https://github.com/SteeltoeOSS/InitializrConfig/issues/41) via [**ZenHub**](https://www.zenhub.com/)
