### ISSUE TITLE
Adding PostgreSQL EFCore registration is commented in startup 

### ISSUE THREAD

**Issue by macsux** [SteeltoeOSS/initializr#136]
Adding PostgreSQL EFCore DI causes registration to be commented out in startup file. It also add comment that is very Cloud Foundry specific

**Comment by ccheetham** [comment]
Issue moved to [SteeltoeOSS/InitializrConfig #43](https://github.com/SteeltoeOSS/InitializrConfig/issues/43) via [**ZenHub**](https://www.zenhub.com/)
