### ISSUE TITLE
Newtonsoft.Json should not be added by default to the template

### ISSUE THREAD

**Issue by macsux** [SteeltoeOSS/initializr#137]
There's no reason to have Newtonsoft.Json as part of default template when ASP.NET Core brings it's own, lighter engine. This should be an optional dependency.

**Comment by ccheetham** [comment]
Issue moved to [SteeltoeOSS/InitializrConfig #44](https://github.com/SteeltoeOSS/InitializrConfig/issues/44) via [**ZenHub**](https://www.zenhub.com/)
