### ISSUE TITLE
Scope validation for DI is disabled by default

### ISSUE THREAD

**Issue by macsux** [SteeltoeOSS/initializr#138]
The template is disabling DI scope validation by default which is not something most people want

`.UseDefaultServiceProvider(configure => configure.ValidateScopes = false)`

**Comment by ccheetham** [comment]
Issue moved to [SteeltoeOSS/InitializrConfig #45](https://github.com/SteeltoeOSS/InitializrConfig/issues/45) via [**ZenHub**](https://www.zenhub.com/)
