### ISSUE TITLE
Adding Actuators are CloudFoundry dependent

### ISSUE THREAD

**Issue by macsux** [SteeltoeOSS/initializr#139]
Adding actuators makes them CloudFoundry dependent. This should be a generic version, and a separate CF specific actuator dependency introduced.

**Comment by ccheetham** [comment]
Issue moved to [SteeltoeOSS/InitializrConfig #46](https://github.com/SteeltoeOSS/InitializrConfig/issues/46) via [**ZenHub**](https://www.zenhub.com/)
