### ISSUE TITLE
Rename Circuit Breaker to Hystrix Circuit Breaker

### ISSUE THREAD

**Issue by macsux** [SteeltoeOSS/initializr#141]
There are multiple libraries that add circuit breaker pattern to code, and TBH Polly is significantly more popular and easier to use then Steeltoe Hystrix version. This will help differentiate the two and offer both.

**Comment by ccheetham** [comment]
Issue moved to [SteeltoeOSS/InitializrConfig #48](https://github.com/SteeltoeOSS/InitializrConfig/issues/48) via [**ZenHub**](https://www.zenhub.com/)
