### ISSUE TITLE
Project name validation error persists when name is corrected

### ISSUE THREAD

**Issue by ddieruf** [SteeltoeOSS/initializr#37]
## Describe the bug
Once the project name gets an invalid name, you can't submit anything

## Steps to reproduce 
1. on start.steeltoe.io input My-Project as the project name
2. click  generate project to fire the validation error message
3. change the project name to MyCompany.ProjectName
2. click  generate project and the validation error persists

## Expected behavior
Once changed the project to something valid, the error should not fire

**Comment by hananiel** [comment]
resolved by #39
