### ISSUE TITLE
.NET Core 3.0 tab missing

### ISSUE THREAD

**Issue by IvanFarkas** [SteeltoeOSS/initializr#46]
## Steps to reproduce 
1. Build
2. Lunch

## Expected behavior
.NET Core 3.0 tab shown, just like at [https://startsteeltoe.cfapps.io/#](https://startsteeltoe.cfapps.io/#)

## Environment:
 - Platform: local
 - OS: Windows 10 Pro (10.0.18970 Build 18970)
 - .NET Core 3.0
 - Steeltoe Version [e.g. 2.3.0]

## Screenshots
**Local**

![image](https://user-images.githubusercontent.com/11818001/66412864-51fe6880-e9c4-11e9-9879-2b6f4e9fead2.png)

**https://startsteeltoe.cfapps.io/#**

![image](https://user-images.githubusercontent.com/11818001/66412509-abb26300-e9c3-11e9-99c5-767e5fc918fa.png)

**Comment by hananiel** [comment]
resolved by #58
