### ISSUE TITLE
Make the site compliant

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/initializr#50]
## Is your feature request related to a problem? Please describe.
Be compliant with lawyers 

## Describe the solution you'd like
You'd want to switch to using the Google Tag Manager code from steeltoe.io, which loads the cookie consent script.  We're also supposed to force ssl.  I'm noticing that start.spring.io doesn't have the requisite legal footer...if you're talking with them, maybe you could pass that info along..should be the same as the spring.io footer.  start.steeltoe.io should be the same as the steeltoe.io footer.
## Additional context

**Comment by hananiel** [comment]
@ddieruf cloey wants to use the GTM code from the steeltoe web site. But given how we did analytics for this project - not sure if that is an option. Can you please look at this and let me know the best way to proceed?

**Comment by ddieruf** [comment]
The way we have initializr set up as it's own property in analytics is a must. It requires its own Tracking Id to properly log events, goals, and other data. If we combined them I would lose quite a few abilities and filters.
