### ISSUE TITLE
[Feedback] Where is netcoreapp3.0 ?

### ISSUE THREAD

**Issue by pghtimwilson** [SteeltoeOSS/initializr#54]
We noticed that the netcoreapp3.0 target framework was bringing in 2.2 dependencies (last week). Is there an eta when netcoreapp3.0 will be added back to the initializr with the correct dependencies?

Thanks.

**Comment by jkonicki** [comment]
Hello @pghtimwilson,

Yes, netcoreapp3.0 caused some breakages in previous Steeltoe 2.x releases.  We have been finalizing our 2.4.0 release which will support netcoreapp3.0.  We are planning to release Steeltoe 2.4.0 (pending no major setbacks) this week and then we will make the necessary changes to Initializr after that.

Thank you.

**Comment by jkonicki** [comment]
If you have any other questions, feel free to reopen this issue.  

Thank you.
