### ISSUE TITLE
Create initial documentation for Initializr

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Initializr#57]

**Comment by ccheetham** [comment]
Replaced by:
* https://github.com/steeltoeoss-incubator/Steeltoe.Initializr.Starter/issues/7
* https://github.com/steeltoeoss-incubator/Steeltoe.Initializr.WebApi/issues/13
* https://github.com/steeltoeoss-incubator/Steeltoe.Initializr.ConfigServer/issues/6
