### ISSUE TITLE
Create a individual library for the generation of projects

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Initializr#63]
Move the project generation code into its own library (nuget) and likely its own repository. 

Releasing this separately will allow others to use it and allow a clear way for upgrading to later versions in the future. 

This library will be used as the basis for the Steeltoe Initializr project generator.

**Comment by ccheetham** [comment]
https://github.com/steeltoeoss-incubator/Steeltoe.Initializr.WebApi
