### ISSUE TITLE
Actuators not running with the netcore 2.1. 

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/initializr#65]
MyCompany.SteeltoeExample.csproj: [NU1107] Version conflict detected for Microsoft.AspNetCore.Http.Abstractions. Install/reference Microsoft.AspNetCore.Http.Abstractions 2.2.0 directly to project MyCompany.SteeltoeExample to resolve this issue.
 MyCompany.SteeltoeExample -> Steeltoe.Management.CloudFoundryCore 2.3.0 -> Steeltoe.Management.EndpointCore 2.3.0 -> Microsoft.AspNetCore.Diagnostics.HealthChecks 2.2.0 -> Microsoft.AspNetCore.Http.Abstractions (>= 2.2.0)
 MyCompany.SteeltoeExample -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.AspNetCore.Http.Abstractions (>= 2.1.1 && < 2.2.0).

**Comment by TimHess** [comment]
I think we already fixed this in 2.x but didn't ship up yet

**Comment by hananiel** [comment]
We are going to remove 2.3.0 of steeltoe as an option. This works find with 2.4.0. Please reopen this issue if you feel the need.
