### ISSUE TITLE
Adding both CF Hosting and Config Server options results in ambiguous references in program.cs file  

### ISSUE THREAD

**Issue by corn-pivotal** [SteeltoeOSS/Initializr#70]
## Describe the bug
When using the initializer and selecting both the Cloud Foundry Hosting and Config Server, the code that is generated for the Program.cs file creates a conflict between the two libraries and results in an error when compiling. The workaround is to remove the hosting reference within the file.

## Steps to reproduce 
1. Select Config Server and Cloud Foundry options in the initializer
2. Generate the code
3. Compile
## Expected behavior
The right reference is added to the Program.cs file and should compile without ambiguous reference message 
## Environment (please complete the following information):
 - Platform:  Cloud Foundry 
 - OS: Windows
 - .NET Version 3.1 
 - Steeltoe Version 2.4.0
 - Template type: NA

**Comment by jkonicki** [comment]
Thank you.  We will be looking into this further.

**Comment by Lechus** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryHostBuilderExtensions.UseCloudFoundryHosting(Microsoft.AspNetCore.Hosting.IWebHostBuilder, int?)' and 'Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHostBuilderExtensions.UseCloudFoundryHosting(Microsoft.AspNetCore.Hosting.IWebHostBuilder, int?)'	SteeltoeExample	E:\SteeltoeExample\Program.cs	30	Active
