### ISSUE TITLE
add support for Steeltoe 3.0

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/Initializr#79]
Steeltoe 3.0 release imminent.  Need to add template support for both Initializr and `dotnet new`.

**Comment by jkonicki** [comment]
Verify 3.0.0.M1 is functional with samples and add to options to pick from.

**Comment by jkonicki** [comment]
3.0.0-m2 is now available.

**Comment by ccheetham** [comment]
transferred to https://github.com/steeltoeoss-incubator/Steeltoe.Initializr.WebApi/issues/14
