### ISSUE TITLE
Dockerfile not formatted correctly

### ISSUE THREAD

**Issue by ddieruf** [SteeltoeOSS/Initializr#84]
When I added in the Dockerfile dependency, line 9 was `COPY. .` and it needs to be `COPY . .`. Also line 18 was `ENTRYPOINT["dotnet","xxx.dll"]` and it should be `ENTRYPOINT ["dotnet","xxx.dll"]`.

**Comment by jkonicki** [comment]
@ddieruf I just used the Dockerfile option and it worked fine.  The spaces are as expected.  
Where there any other config options you selected?

**Comment by ddieruf** [comment]
I had chose Steeltoe 2.4, netcore31, project name: ”Steeltoe_observability”, dependencies: “Actuators, DynamicLogging, Dockerfile”

**Comment by jkonicki** [comment]
I have tried on both MacOSX and Windows OS, but I am unable to reproduce.

**Comment by ddieruf** [comment]
Looks like a ghost. Closing.
