### ISSUE TITLE
Search dependencies feature is causing the screen to turn white

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Initializr#98]
## Describe the bug
When searching for dependencies on the Web App, once you select a dependency the screen turns white.

## Steps to reproduce 
1. Search for dependency
2. Select Dependency
3. Watch the screen turn white

## Expected behavior
The dep is selected and added to dependency for application

## Environment (please complete the following information):
-  Chrome, Firefox

**Comment by ccheetham** [comment]
Fixed by reverting to older libraries: f0baa761e6f04dd33f813eefaa890d8f94b0bbcc
